"""create material stocks table

Revision ID: 8de8eaab9683
Revises: 6719bfd8f4fa
Create Date: 2024-12-14 18:39:15.291772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de8eaab9683'
down_revision: Union[str, None] = '6719bfd8f4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('reserved', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_stocks_id'), 'material_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_material_stocks_material_id'), 'material_stocks', ['material_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_stocks_material_id'), table_name='material_stocks')
    op.drop_index(op.f('ix_material_stocks_id'), table_name='material_stocks')
    op.drop_table('material_stocks')
    # ### end Alembic commands ###
