"""update_material_stock_model

Revision ID: b30f7115edbd
Revises: f0caf70a08ce
Create Date: 2024-12-14 20:11:45.436077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30f7115edbd'
down_revision: Union[str, None] = 'f0caf70a08ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_stocks', sa.Column('material_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_stocks', 'material_description')
    # ### end Alembic commands ###
