"""update_pydantic_models

Revision ID: dde7e82c47d9
Revises: 6bc8e3c2b7b5
Create Date: 2024-12-18 20:29:17.294717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde7e82c47d9'
down_revision: Union[str, None] = '6bc8e3c2b7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
